### ISSUE TITLE
convert.py

### ISSUE THREAD

**Issue by yggdrasil75** [city96/ComfyUI-GGUF#119]
Traceback (most recent call last):
  File "/gits/ComfyUI/custom_nodes/ComfyUI-GGUF/tools/convert.py", line 165, in handle_tensors
    data = gguf.quants.quantize(data, data_qtype)
AttributeError: module 'gguf.quants' has no attribute 'quantize'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gits/ComfyUI/custom_nodes/ComfyUI-GGUF/tools/convert.py", line 195, in <module>
    handle_tensors(path, writer, state_dict)
  File "/gits/ComfyUI/custom_nodes/ComfyUI-GGUF/tools/convert.py", line 166, in handle_tensors
    except (AttributeError, gguf.QuantError) as e:
AttributeError: module 'gguf' has no attribute 'QuantError'

get this error when trying to convert a model to gguf. could more info about what is needed to convert models be added?

**Comment by fractal-fumbler** [comment]
@yggdrasil75, be cautious that script needs the llama.cpp version of gguf-py. 
more info https://github.com/city96/ComfyUI-GGUF/tree/main/tools
