### ISSUE TITLE
UnetLoaderGGUF cannot reshape array of size 615776 into shape (12288,1728)   "i spent 2 days and wdidn't resolved please any solution

### ISSUE THREAD

**Issue by habibteyeb** [city96/ComfyUI-GGUF#169]
!!! Exception during processing !!! cannot reshape array of size 615776 into shape (12288,1728)
Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 199, in get_output_data
    return_values = mapnode_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 170, in mapnode_over_list
    process_inputs(input_dict, i)
  File "/workspace/ComfyUI/execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(inputs))
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-GGUF/nodes.py", line 258, in load_unet
    sd = gguf_sd_loader(unet_path)
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-GGUF/nodes.py", line 39, in gguf_sd_loader
    reader = gguf.GGUFReader(path)
  File "/workspace/ComfyUI/venv/lib/python3.10/site-packages/gguf/gguf_reader.py", line 130, in init**
    self._build_tensors(offs, tensors_fields)
  File "/workspace/ComfyUI/venv/lib/python3.10/site-packages/gguf/gguf_reader.py", line 314, in buildtensors
    data = self._get(data_offs, item_type, item_count).reshape(np_dims),
ValueError: cannot reshape array of size 615776 into shape (12288,1728)" the error with unet loader gguf

**Comment by habibteyeb** [comment]
well thank you, my gguf model doesn't completed installing.
