### ISSUE TITLE
MPS device support

### ISSUE THREAD

**Issue by a-ru2016** [city96/ComfyUI-GGUF#27]
An error occurred on my M1 macbook pro. Can't you make it work on mps devices as well?

```
ggml_sd_loader:
 GGMLQuantizationType.F16      476
 GGMLQuantizationType.Q4_0     304


model weight dtype torch.bfloat16, manual cast: None
model_type FLUX
Requested to load FluxClipModel_
Loading 1 new model
clip missing: ['text_projection.weight']
Requested to load Flux
Loading 1 new model
  0%|                                                    | 0/20 [00:00<?, ?it/s]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
  0%|                                                    | 0/20 [00:02<?, ?it/s]
!!! Exception during processing !!! The operator 'aten::__rshift__.Tensor' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
Traceback (most recent call last):
  File "/Users/myname/ComfyUI/execution.py", line 313, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/Users/myname/ComfyUI/execution.py", line 188, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/Users/myname/ComfyUI/execution.py", line 165, in map_node_over_list
    process_inputs(input_dict, i)
  File "/Users/myname/ComfyUI/execution.py", line 154, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/Users/myname/ComfyUI/comfy_extras/nodes_custom_sampler.py", line 455, in sample
    samples = comfy.sample.sample_custom(model, noise, cfg, sampler, sigmas, positive, negative, latent_image, noise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise_seed)
  File "/Users/myname/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 434, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "/Users/myname/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/sampling.py", line 116, in acn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "/Users/myname/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 116, in uncond_multiplier_check_cn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "/Users/myname/ComfyUI/comfy/sample.py", line 48, in sample_custom
    samples = comfy.samplers.sample(model, noise, positive, negative, cfg, model.load_device, sampler, sigmas, model_options=model.model_options, latent_image=latent_image, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/Users/myname/ComfyUI/comfy/samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/Users/myname/ComfyUI/comfy/samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/Users/myname/ComfyUI/comfy/samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/Users/myname/ComfyUI/comfy/samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/Users/myname/ComfyUI/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/myname/ComfyUI/comfy/k_diffusion/sampling.py", line 143, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/Users/myname/ComfyUI/comfy/samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/Users/myname/ComfyUI/comfy/samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/Users/myname/ComfyUI/comfy/samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/Users/myname/ComfyUI/comfy/samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/Users/myname/ComfyUI/comfy/samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/Users/myname/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 68, in apply_model_uncond_cleanup_wrapper
    return orig_apply_model(self, *args, **kwargs)
  File "/Users/myname/ComfyUI/comfy/model_base.py", line 145, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/Users/myname/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/myname/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/myname/ComfyUI/comfy/ldm/flux/model.py", line 150, in forward
    out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control)
  File "/Users/myname/ComfyUI/comfy/ldm/flux/model.py", line 118, in forward_orig
    img, txt = self.double_blocks[i](img=img, txt=txt, vec=vec, pe=pe)
  File "/Users/myname/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/myname/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/myname/ComfyUI/comfy/ldm/flux/layers.py", line 148, in forward
    img_mod1, img_mod2 = self.img_mod(vec)
  File "/Users/myname/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/myname/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/myname/ComfyUI/comfy/ldm/flux/layers.py", line 110, in forward
    out = self.lin(nn.functional.silu(vec))[:, None, :].chunk(self.multiplier, dim=-1)
  File "/Users/myname/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/myname/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/myname/ComfyUI/custom_nodes/ComfyUI-GGUF/ops.py", line 99, in forward
    weight, bias = self.get_weights(x.dtype)
  File "/Users/myname/ComfyUI/custom_nodes/ComfyUI-GGUF/ops.py", line 78, in get_weights
    weight = dequantize_tensor(self.weight, dtype)
  File "/Users/myname/ComfyUI/custom_nodes/ComfyUI-GGUF/dequant.py", line 20, in dequantize_tensor
    out = dequantize(data, qtype, oshape, dtype=None)
  File "/Users/myname/ComfyUI/custom_nodes/ComfyUI-GGUF/dequant.py", line 40, in dequantize
    blocks = dequantize_blocks(blocks, block_size, type_size, dtype)
  File "/Users/myname/ComfyUI/custom_nodes/ComfyUI-GGUF/dequant.py", line 107, in dequantize_blocks_Q4_0
    qs = qs.reshape((n_blocks, -1, 1, block_size // 2)) >> torch.tensor([0, 4], device=d.device, dtype=torch.uint8).reshape((1, 1, 2, 1))
NotImplementedError: The operator 'aten::__rshift__.Tensor' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

```

**Comment by city96** [comment]
I'm not too sure what I could do about bitshift not being supported, since running it on the CPU or falling back to numpy would land you in the minutes/it zone lol.

I mean, you can try since it has it right in the error message.

>As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op.

If it somehow does run at any kind of decent speed I'll add that to the readme.

**Comment by city96** [comment]
Could either of you try something? Just curious if running it on the CPU would help or if it would still fail / still be slow.

[On this line](https://github.com/city96/ComfyUI-GGUF/blob/1ebce77a446407c2a48802111816401051ab9798/dequant.py#L18) in dequant.py

Replace this: 

```py
        out = dequantize(data, qtype, oshape, dtype=None)
```

With either of these:

```py
        out = dequantize(data.to("cpu"), qtype, oshape, dtype=None).to(data.device)
```

```py
        out = dequantize(data.to("cpu"), qtype, oshape, dtype=torch.float32).to(data.device)
```

**Comment by jxy** [comment]
CPU is slow, but doing division instead of rshift works on MPS,
```
qs = qs.reshape((n_blocks, -1, 1, block_size // 2)) // torch.tensor([1, 16], device=d.device, dtype=torch.uint8).reshape((1, 1, 2, 1))
```

**Comment by JosNun** [comment]
I can give it a try when I get a chance, but that likely won't be until tomorrow evening at least. Thanks!

**Comment by discordinated** [comment]
> CPU is slow, but doing division instead of rshift works on MPS,
> 
> ```
> qs = qs.reshape((n_blocks, -1, 1, block_size // 2)) // torch.tensor([1, 16], device=d.device, dtype=torch.uint8).reshape((1, 1, 2, 1))
> ```

This works for Q4_1 but only seems marginally faster than just using Q8 where it works natively. Struggling to get Q5, Q6 etc to work with the same line.

**Comment by edwios** [comment]
I am using `flux1-dev-Q8_0.gguf` on a M1 Max (Python 3.11.6, torch 2.3.1), simple prompt of approx 70 tokens yielded an average of 15.7s/it. Not too bad considering no other optimisations have been done with this first generation of FLUX implementation. `PYTORCH_ENABLE_MPS_FALLBACK` must enable, however.

**Comment by a-ru2016** [comment]
Now it works natively by downloading pytorch nightly.

**Comment by JosNun** [comment]
For peeps looking for more info, support was added in this commit https://github.com/pytorch/pytorch/commit/3bf6be457d40034aa4b603b7ea1b8977051221ed

**Comment by Moses2917** [comment]
Can confirm it works!
I installed the latest version of PyTorch nightly and I am able to run flux gruff natively on my mps device.
Just make sure if you already have PyTorch installed to include the "-U" tag to upgrade to nightly.

**Comment by JosNun** [comment]
Just out of curiosity, was there any noticeable performance improvements?

**Comment by Moses2917** [comment]
I am running it on an M3 Pro with 18GB of RAM, in both cases I just ran main.py with no args(besides --cpu for only cpu)
The results are like a night and day difference in terms of performance, running it on MPS is way faster, which makes sense since its made for that, and it was somewhat useable, whereas on the CPU it took way longer. I have provided the numbers for reference.
```
MPS native: 27s/it Total time: 133s
```
```
CPU: 100s/it Total time: 423s
```

**Comment by RockyFong** [comment]
> Can confirm it works! I installed the latest version of PyTorch nightly and I am able to run flux gruff natively on my mps device. Just make sure if you already have PyTorch installed to include the "-U" tag to upgrade to nightly.

Do you mean GGUF supports Apple Silicon's GPU? Could you show how you did it, please?

**Comment by Moses2917** [comment]
Yeah, I downloaded the extension, the necessary model and then I also got the T5 encoder in GGUF and I just ran it and it worked, but you have to pip install the latest version of PyTorch nightly which will allow you to use the Apple Silicon.

**Comment by RockyFong** [comment]
> Yeah, I downloaded the extension, the necessary model and then I also got the T5 encoder in GGUF and I just ran it and it worked, but you have to pip install the latest version of PyTorch nightly which will allow you to use the Apple Silicon.

I guess you ran it with 
PYTORCH_ENABLE_MPS_FALLBACK=1 python main.py
right?
