### ISSUE TITLE
Cannot convert to gguf on sdxl

### ISSUE THREAD

**Issue by NeuroDonu** [city96/ComfyUI-GGUF#42]
Hi!
I wanted to quantize sdxl-lightning (to run it on my 2gb video card) but I can not do it, because if I try to convert it to Q2_K format I get this error:
Traceback (most recent call last):
  File "/content/llama.cpp/gguf-py/convert.py", line 160, in <module>
    handle_tensors(args, writer, state_dict)
  File "/content/llama.cpp/gguf-py/convert.py", line 130, in handle_tensors
    data = gguf.quants.quantize(data, data_qtype)
  File "/content/llama.cpp/gguf-py/gguf/quants.py", line 62, in quantize
    return q.quantize(data)
  File "/content/llama.cpp/gguf-py/gguf/quants.py", line 194, in quantize
    return cls.__quantize_array(tensor)
  File "/content/llama.cpp/gguf-py/gguf/quants.py", line 168, in __quantize_array
    return _apply_over_grouped_rows(cls.quantize_rows, arr=array, otype=np.uint8, oshape=cls.__shape_to_bytes(array.shape))
  File "/content/llama.cpp/gguf-py/gguf/quants.py", line 37, in _apply_over_grouped_rows
    np.concatenate([func(group).ravel() for group in np.array_split(rows, n_groups)], axis=0, out=out)
  File "/content/llama.cpp/gguf-py/gguf/quants.py", line 37, in <listcomp>
    np.concatenate([func(group).ravel() for group in np.array_split(rows, n_groups)], axis=0, out=out)
  File "/content/llama.cpp/gguf-py/gguf/quants.py", line 142, in quantize_rows
    blocks = cls.quantize_blocks(blocks)
  File "/content/llama.cpp/gguf-py/gguf/quants.py", line 129, in quantize_blocks
    raise NotImplementedError
NotImplementedError
And if Q4_O this error:
Traceback (most recent call last):
  File "/content/llama.cpp/gguf-py/convert.py", line 160, in <module>
    handle_tensors(args, writer, state_dict)
  File "/content/llama.cpp/gguf-py/convert.py", line 140, in handle_tensors
    assert len(key) < 64, f"Invalid key length! Cannot store in gguf file. {key}"
AssertionError: Invalid key length! Cannot store in gguf file. down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_k.weight

How to fix this?
Edited:
i use this unet: https://huggingface.co/ByteDance/SDXL-Lightning/blob/main/sdxl_lightning_4step_unet.safetensors

**Comment by city96** [comment]
There would be almost no benefit from converting SDXL. Unlike a diffusion model the size reduction would be way smaller as conv2d layers cannot be quantized. This only works well for diffusion transformer models that have lots of linear layers.

**Comment by NeuroDonu** [comment]
Understood, thank you. Then I close the issue
