### ISSUE TITLE
cannot reshape array of size 11575520 into shape (18432,3264)

### ISSUE THREAD

**Issue by 1247862674** [city96/ComfyUI-GGUF#86]
我该如何解决这个错误
![image](https://github.com/user-attachments/assets/ce6daaca-2a13-40b4-94ad-24bfb5dbf817)

**Comment by city96** [comment]
What model are you using? Since that's failing while reading the data it's either a corrupt/invalid model file or your gguf package is out of date.

**Comment by 1247862674** [comment]
I am using  flux1-dev-Q8_0.gguf .I tried different models and got the same error. I can only judge whether it is damaged based on the size of the model. It looks normal.
what do i need to do？

**Comment by 1247862674** [comment]
![image](https://github.com/user-attachments/assets/f09e366b-1f3b-4c5d-825b-e46876d96a9b)
This is my workflow

**Comment by heskey9** [comment]
any solution?

**Comment by DrSakuu** [comment]
I get the same error, using [Flux.1-Dev GGUF Q8](https://civitai.com/models/647237?modelVersionId=724149) from Civitai with [their example workflow](https://education.civitai.com/quickstart-guide-to-flux-1/#gguf-quantized-models-example-workflows-read-me) (lora bypassed)

# ComfyUI Error Report
## Error Details
- **Node Type:** UnetLoaderGGUF
- **Exception Type:** ValueError
- **Exception Message:** cannot reshape array of size 15696677 into shape (3072,13056)
## Stack Trace
```
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 258, in load_unet
    sd = gguf_sd_loader(unet_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 39, in gguf_sd_loader
    reader = gguf.GGUFReader(path)
             ^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\gguf\gguf_reader.py", line 130, in __init__
    self._build_tensors(offs, tensors_fields)

  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\gguf\gguf_reader.py", line 314, in _build_tensors
    data = self._get(data_offs, item_type, item_count).reshape(np_dims),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.2-84-gd1cdf51
- **Arguments:** ComfyUI\main.py --windows-standalone-build --output-directory C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\OUT
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3090 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25756696576
  - **VRAM Free:** 24418189312
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-10-02 10:15:24,720 - root - INFO - Total VRAM 24564 MB, total RAM 65461 MB
2024-10-02 10:15:24,721 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-02 10:15:24,722 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-02 10:15:24,722 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3090 Ti : cudaMallocAsync
2024-10-02 10:15:25,444 - root - INFO - Using pytorch cross attention
2024-10-02 10:15:26,662 - root - INFO - [Prompt Server] web root: C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\web
2024-10-02 10:15:29,229 - root - INFO - 
Import times for custom nodes:
2024-10-02 10:15:29,229 - root - INFO -    0.0 seconds: C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-02 10:15:29,229 - root - INFO -    0.0 seconds: C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-10-02 10:15:29,229 - root - INFO -    0.0 seconds: C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
2024-10-02 10:15:29,229 - root - INFO -    0.0 seconds: C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
2024-10-02 10:15:29,229 - root - INFO -    0.0 seconds: C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-10-02 10:15:29,229 - root - INFO -    0.0 seconds: C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-10-02 10:15:29,229 - root - INFO -    0.0 seconds: C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr
2024-10-02 10:15:29,229 - root - INFO -    0.0 seconds: C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-10-02 10:15:29,229 - root - INFO -    0.1 seconds: C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-10-02 10:15:29,229 - root - INFO -    0.1 seconds: C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-10-02 10:15:29,229 - root - INFO -    0.2 seconds: C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-02 10:15:29,229 - root - INFO -    0.4 seconds: C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-10-02 10:15:29,229 - root - INFO -    1.3 seconds: C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-10-02 10:15:29,229 - root - INFO - 
2024-10-02 10:15:29,236 - root - INFO - Setting output directory to: C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\OUT
2024-10-02 10:15:29,236 - root - INFO - Starting server

2024-10-02 10:15:29,236 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-02 10:15:37,618 - root - INFO - got prompt
2024-10-02 10:15:37,632 - root - INFO - Using pytorch attention in VAE
2024-10-02 10:15:37,634 - root - INFO - Using pytorch attention in VAE
2024-10-02 10:15:37,888 - root - ERROR - !!! Exception during processing !!! cannot reshape array of size 15696677 into shape (3072,13056)
2024-10-02 10:15:37,889 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 258, in load_unet
    sd = gguf_sd_loader(unet_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 39, in gguf_sd_loader
    reader = gguf.GGUFReader(path)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\gguf\gguf_reader.py", line 130, in __init__
    self._build_tensors(offs, tensors_fields)
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\gguf\gguf_reader.py", line 314, in _build_tensors
    data = self._get(data_offs, item_type, item_count).reshape(np_dims),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 15696677 into shape (3072,13056)

2024-10-02 10:15:37,890 - root - INFO - Prompt executed in 0.27 seconds
2024-10-02 10:18:56,721 - root - INFO - got prompt
2024-10-02 10:18:56,762 - root - ERROR - !!! Exception during processing !!! cannot reshape array of size 15696677 into shape (3072,13056)
2024-10-02 10:18:56,763 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 258, in load_unet
    sd = gguf_sd_loader(unet_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 39, in gguf_sd_loader
    reader = gguf.GGUFReader(path)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\gguf\gguf_reader.py", line 130, in __init__
    self._build_tensors(offs, tensors_fields)
  File "C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\gguf\gguf_reader.py", line 314, in _build_tensors
    data = self._get(data_offs, item_type, item_count).reshape(np_dims),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 15696677 into shape (3072,13056)

2024-10-02 10:18:56,764 - root - INFO - Prompt executed in 0.04 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":22,"last_link_id":30,"nodes":[{"id":4,"type":"VAELoader","pos":{"0":-826,"1":961},"size":{"0":315,"1":58},"flags":{"pinned":true},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[2],"slot_index":0,"shape":3}],"title":"VAE Loader","properties":{"Node name for S&R":"VAELoader"},"widgets_values":["ae.safetensors"],"color":"#322","bgcolor":"#533"},{"id":19,"type":"LoraLoaderModelOnly","pos":{"0":-826,"1":846},"size":{"0":315,"1":82},"flags":{"pinned":true},"order":10,"mode":4,"inputs":[{"name":"model","type":"MODEL","link":29}],"outputs":[{"name":"MODEL","type":"MODEL","links":[30],"slot_index":0,"shape":3}],"title":"Lora Loader","properties":{"Node name for S&R":"LoraLoaderModelOnly"},"widgets_values":["lora_sakmiyo_ponyxl_20241002.safetensors",0],"color":"#322","bgcolor":"#533"},{"id":1,"type":"DualCLIPLoaderGGUF","pos":{"0":-826,"1":703},"size":{"0":315,"1":106},"flags":{"pinned":true},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[14],"shape":3}],"title":"Dual CLIP Loader (GGUF)","properties":{"Node name for S&R":"DualCLIPLoaderGGUF"},"widgets_values":["clip_l.safetensors","t5xxl_fp8_e4m3fn.safetensors","flux"],"color":"#322","bgcolor":"#533"},{"id":2,"type":"UnetLoaderGGUF","pos":{"0":-827,"1":604},"size":{"0":314.87799072265625,"1":60.64590835571289},"flags":{"pinned":true},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[28,29],"slot_index":0,"shape":3}],"title":"Unet Model Loader (GGUF)","properties":{"Node name for S&R":"UnetLoaderGGUF"},"widgets_values":["flux1-dev-Q8_0.gguf"],"color":"#322","bgcolor":"#533"},{"id":22,"type":"UNETLoader","pos":{"0":-829,"1":481},"size":{"0":315,"1":82},"flags":{"pinned":true},"order":3,"mode":4,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"UNETLoader"},"widgets_values":["flux_dev.safetensors","fp8_e4m3fn"],"color":"#322","bgcolor":"#533"},{"id":8,"type":"VAEDecode","pos":{"0":-826,"1":1079},"size":{"0":210,"1":46},"flags":{"collapsed":true,"pinned":true},"order":14,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":8},{"name":"vae","type":"VAE","link":2}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[19],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[],"color":"#222","bgcolor":"#000"},{"id":6,"type":"BasicGuider","pos":{"0":-641,"1":1079},"size":{"0":241.79998779296875,"1":46},"flags":{"collapsed":true,"pinned":true},"order":12,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":30},{"name":"conditioning","type":"CONDITIONING","link":5}],"outputs":[{"name":"GUIDER","type":"GUIDER","links":[9],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"BasicGuider"},"widgets_values":[],"color":"#222","bgcolor":"#000"},{"id":11,"type":"CLIPTextEncode","pos":{"0":-478,"1":221},"size":{"0":434.18402099609375,"1":205.4606170654297},"flags":{"pinned":true},"order":8,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":14}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[13],"shape":3}],"title":"Prompt","properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["a beautiful young woman, thin, athletic, wearing a bridal dress on a tropical beach with flowers in her hair, happy expression, palm trees, bright blue sparkly ocean water, shallow depth of field, bokeh, professional photography with cinematic lighting"],"color":"#232","bgcolor":"#353"},{"id":17,"type":"SamplerCustomAdvanced","pos":{"0":-479,"1":462},"size":{"0":436.4391174316406,"1":619.092529296875},"flags":{"collapsed":false,"pinned":true},"order":13,"mode":0,"inputs":[{"name":"noise","type":"NOISE","link":10},{"name":"guider","type":"GUIDER","link":9},{"name":"sampler","type":"SAMPLER","link":11},{"name":"sigmas","type":"SIGMAS","link":15},{"name":"latent_image","type":"LATENT","link":12}],"outputs":[{"name":"output","type":"LATENT","links":[8],"slot_index":0,"shape":3},{"name":"denoised_output","type":"LATENT","links":null,"shape":3}],"title":"Image Preview","properties":{"Node name for S&R":"SamplerCustomAdvanced"},"widgets_values":[],"color":"#232","bgcolor":"#353"},{"id":13,"type":"RandomNoise","pos":{"0":-12,"1":224},"size":{"0":268.8857421875,"1":82},"flags":{"pinned":true},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"NOISE","type":"NOISE","links":[10],"slot_index":0,"shape":3}],"title":"Seed","properties":{"Node name for S&R":"RandomNoise"},"widgets_values":[688674626017361,"randomize"],"color":"#223","bgcolor":"#335"},{"id":15,"type":"BasicScheduler","pos":{"0":-12,"1":341},"size":{"0":267.7461242675781,"1":106},"flags":{"pinned":true},"order":9,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":28}],"outputs":[{"name":"SIGMAS","type":"SIGMAS","links":[15],"slot_index":0,"shape":3}],"title":"Scheduler","properties":{"Node name for S&R":"BasicScheduler"},"widgets_values":["normal",25,1],"color":"#223","bgcolor":"#335"},{"id":14,"type":"KSamplerSelect","pos":{"0":-13,"1":484},"size":{"0":268.12298583984375,"1":58},"flags":{"pinned":true},"order":5,"mode":0,"inputs":[],"outputs":[{"name":"SAMPLER","type":"SAMPLER","links":[11],"slot_index":0,"shape":3}],"title":"Sampler","properties":{"Node name for S&R":"KSamplerSelect"},"widgets_values":["euler"],"color":"#223","bgcolor":"#335"},{"id":9,"type":"FluxGuidance","pos":{"0":-14,"1":578},"size":{"0":271.3692321777344,"1":58},"flags":{"pinned":true},"order":11,"mode":0,"inputs":[{"name":"conditioning","type":"CONDITIONING","link":13}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[5],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"FluxGuidance"},"widgets_values":[3.5],"color":"#223","bgcolor":"#335"},{"id":12,"type":"EmptySD3LatentImage","pos":{"0":-15,"1":672},"size":{"0":274.3692321777344,"1":109.2433090209961},"flags":{"pinned":true},"order":6,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[12],"slot_index":0,"shape":3}],"title":"Picture size","properties":{"Node name for S&R":"EmptySD3LatentImage"},"widgets_values":[832,1216,1],"color":"#223","bgcolor":"#335"},{"id":18,"type":"SaveImage","pos":{"0":280,"1":174},"size":{"0":578.8286743164062,"1":914.6400146484375},"flags":{"pinned":true},"order":15,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":19}],"outputs":[],"title":"Saved image","properties":{"Node name for S&R":"SaveImage"},"widgets_values":["ComfyUI"],"color":"#323","bgcolor":"#535"},{"id":5,"type":"Note","pos":{"0":-839,"1":167},"size":{"0":337.3487548828125,"1":211.17466735839844},"flags":{"pinned":false},"order":7,"mode":0,"inputs":[],"outputs":[],"properties":{"text":""},"widgets_values":["Simple GGUF Flux Workflow, created for Civitai's Quickstart Guide to Flux -  https://education.civitai.com/quickstart-guide-to-flux-1\n\nDownload the GGUF-Q8 model from https://civitai.com/models/647237?modelVersionId=724149 and place it in the ComfyUI\\models\\unet folder. "],"color":"#432","bgcolor":"#653"}],"links":[[2,4,0,8,1,"VAE"],[5,9,0,6,1,"CONDITIONING"],[8,17,0,8,0,"LATENT"],[9,6,0,17,1,"GUIDER"],[10,13,0,17,0,"NOISE"],[11,14,0,17,2,"SAMPLER"],[12,12,0,17,4,"LATENT"],[13,11,0,9,0,"CONDITIONING"],[14,1,0,11,0,"CLIP"],[15,15,0,17,3,"SIGMAS"],[19,8,0,18,0,"IMAGE"],[28,2,0,15,0,"MODEL"],[29,2,0,19,0,"MODEL"],[30,19,0,6,0,"MODEL"]],"groups":[{"title":"Loaders","bounding":[-839,395,337,638],"color":"#3f789e","font_size":24,"flags":{}},{"title":"Prompt & Preview","bounding":[-488,140,458,953],"color":"#8A8","font_size":24,"flags":{}},{"title":"Settings","bounding":[-22,140,289,952],"color":"#3f789e","font_size":24,"flags":{}}],"config":{},"extra":{"ds":{"scale":0.9646149645000023,"offset":[1025.6355327021574,88.69710027957768]}},"version":0.4}
```

## Additional Context
Using [Flux.1-Dev GGUF Q8](https://civitai.com/models/647237?modelVersionId=724149) from Civitai with [their example workflow](https://education.civitai.com/quickstart-guide-to-flux-1/#gguf-quantized-models-example-workflows-read-me) (lora bypassed)

I'm not sure why it says Python Version: 3.11.9, ComfyUI embedded python is version 3.10.11
```
C:\Users\Sakuu-Holo\Desktop\Ohjelmat\AI\ComfyUI_windows_portable\python_embeded\Scripts>python.exe --version
Python 3.10.11
```
