### ISSUE TITLE
LORA issues

### ISSUE THREAD

**Issue by ManOrMonster** [city96/ComfyUI-GGUF#98]
Before the latest update, LORAs were apparently being applied again after every generation, so after 2-3 generations images started to get messed up.

After the latest update, LORAs cause massive slowdown when generating (2-3 times slower). Then after 2-3 generations, I get this error:

```
!!! Exception during processing !!! Boolean value of Tensor with more than one value is ambiguous
Traceback (most recent call last):
  File "C:\stable-diffusion\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\stable-diffusion\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\stable-diffusion\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\stable-diffusion\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\stable-diffusion\ComfyUI\comfy_extras\nodes_custom_sampler.py", line 612, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
  File "C:\stable-diffusion\ComfyUI\comfy\samplers.py", line 706, in sample
    self.inner_model, self.conds, self.loaded_models = comfy.sampler_helpers.prepare_sampling(self.model_patcher, noise.shape, self.conds)
  File "C:\stable-diffusion\ComfyUI\comfy\sampler_helpers.py", line 66, in prepare_sampling
    comfy.model_management.load_models_gpu([model] + models, memory_required=memory_required, minimum_memory_required=minimum_memory_required)
  File "C:\stable-diffusion\ComfyUI\comfy\model_management.py", line 504, in load_models_gpu
    use_more_memory(free_mem - minimum_memory_required, models_already_loaded, d)
  File "C:\stable-diffusion\ComfyUI\comfy\model_management.py", line 362, in use_more_memory
    extra_memory -= m.model_use_more_vram(extra_memory)
  File "C:\stable-diffusion\ComfyUI\comfy\model_management.py", line 354, in model_use_more_vram
    return self.model.partially_load(self.device, extra_memory)
  File "C:\stable-diffusion\ComfyUI\comfy\model_patcher.py", line 524, in partially_load
    self.load(device_to, lowvram_model_memory=current_used + extra_memory, full_load=full_load)
  File "C:\stable-diffusion\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 187, in load
    super().load(*args, force_patch_weights=True, **kwargs)
  File "C:\stable-diffusion\ComfyUI\comfy\model_patcher.py", line 393, in load
    self.patch_weight_to_device(weight_key, device_to=device_to)
  File "C:\stable-diffusion\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 151, in patch_weight_to_device
    if patch not in out_weight.patches:
RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```

**Comment by ManOrMonster** [comment]
I was using the Advanced UNet GGUF loader set to "Target, Target, True". When I set to default and off, it's no longer causing the error. There's still quite a bit of slowdown when generating with LORAs though.

**Comment by city96** [comment]
Should be fixed, I don't think there's a reason to allow applying the weight twice so instead of checking the new logic replaces them now. The slowdown is mostly normal, unless you mean compared to previous versions, in which case reopen and I'll look into it.
